/**
 * Bitcoind
 * The REST API can be enabled with the `-rest` option. The interface runs on the same port as the JSON-RPC interface, by default port `8332` for **mainnet**, port `18332` for **testnet**, and port `18443` for **regtest**.
 *
 * OpenAPI spec version: 0.16
 * Contact: johan@lepetitbloc.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/BIPReject'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./BIPReject'));
  } else {
    // Browser globals (root is window)
    if (!root.BitcoindRestClient) {
      root.BitcoindRestClient = {};
    }
    root.BitcoindRestClient.BIP = factory(root.BitcoindRestClient.ApiClient, root.BitcoindRestClient.BIPReject);
  }
}(this, function(ApiClient, BIPReject) {
  'use strict';




  /**
   * The BIP model module.
   * @module model/BIP
   * @version 0.16
   */

  /**
   * Constructs a new <code>BIP</code>.
   * @alias module:model/BIP
   * @class
   */
  var exports = function() {
    var _this = this;




  };

  /**
   * Constructs a <code>BIP</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/BIP} obj Optional instance to populate.
   * @return {module:model/BIP} The populated <code>BIP</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'String');
      }
      if (data.hasOwnProperty('version')) {
        obj['version'] = ApiClient.convertToType(data['version'], 'Number');
      }
      if (data.hasOwnProperty('reject')) {
        obj['reject'] = BIPReject.constructFromObject(data['reject']);
      }
    }
    return obj;
  }

  /**
   * The BIP number, or ? before being assigned
   * @member {String} id
   */
  exports.prototype['id'] = undefined;
  /**
   * The BIP version number
   * @member {Number} version
   */
  exports.prototype['version'] = undefined;
  /**
   * @member {module:model/BIPReject} reject
   */
  exports.prototype['reject'] = undefined;



  return exports;
}));


