/**
 * Bitcoind
 * The REST API can be enabled with the `-rest` option. The interface runs on the same port as the JSON-RPC interface, by default port `8332` for **mainnet**, port `18332` for **testnet**, and port `18443` for **regtest**.
 *
 * OpenAPI spec version: 0.16
 * Contact: johan@lepetitbloc.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.BitcoindRestClient) {
      root.BitcoindRestClient = {};
    }
    root.BitcoindRestClient.BIP9 = factory(root.BitcoindRestClient.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The BIP9 model module.
   * @module model/BIP9
   * @version 0.16
   */

  /**
   * Constructs a new <code>BIP9</code>.
   * @alias module:model/BIP9
   * @class
   */
  var exports = function() {
    var _this = this;





  };

  /**
   * Constructs a <code>BIP9</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/BIP9} obj Optional instance to populate.
   * @return {module:model/BIP9} The populated <code>BIP9</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('status')) {
        obj['status'] = ApiClient.convertToType(data['status'], 'String');
      }
      if (data.hasOwnProperty('startTime')) {
        obj['startTime'] = ApiClient.convertToType(data['startTime'], 'Number');
      }
      if (data.hasOwnProperty('timeout')) {
        obj['timeout'] = ApiClient.convertToType(data['timeout'], 'Number');
      }
      if (data.hasOwnProperty('since')) {
        obj['since'] = ApiClient.convertToType(data['since'], 'Number');
      }
    }
    return obj;
  }

  /**
   * @member {module:model/BIP9.StatusEnum} status
   */
  exports.prototype['status'] = undefined;
  /**
   * The starttime specifies a minimum median time past of a block at which the bit gains its meaning.
   * @member {Number} startTime
   */
  exports.prototype['startTime'] = undefined;
  /**
   * The timeout specifies a time at which the deployment is considered failed. If the median time past of a block >= timeout and the soft fork has not yet locked in (including this block's bit state), the deployment is considered failed on all descendants of the block.
   * @member {Number} timeout
   */
  exports.prototype['timeout'] = undefined;
  /**
   * @member {Number} since
   */
  exports.prototype['since'] = undefined;


  /**
   * Allowed values for the <code>status</code> property.
   * @enum {String}
   * @readonly
   */
  exports.StatusEnum = {
    /**
     * value: "defined"
     * @const
     */
    "defined": "defined",
    /**
     * value: "started"
     * @const
     */
    "started": "started",
    /**
     * value: "locked_in"
     * @const
     */
    "locked_in": "locked_in",
    /**
     * value: "active"
     * @const
     */
    "active": "active",
    /**
     * value: "failed"
     * @const
     */
    "failed": "failed"  };


  return exports;
}));


