/**
 * Bitcoind
 * The REST API can be enabled with the `-rest` option. The interface runs on the same port as the JSON-RPC interface, by default port `8332` for **mainnet**, port `18332` for **testnet**, and port `18443` for **regtest**.
 *
 * OpenAPI spec version: 0.16
 * Contact: johan@lepetitbloc.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Transaction'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Transaction'));
  } else {
    // Browser globals (root is window)
    if (!root.BitcoindRestClient) {
      root.BitcoindRestClient = {};
    }
    root.BitcoindRestClient.InlineResponseDefault = factory(root.BitcoindRestClient.ApiClient, root.BitcoindRestClient.Transaction);
  }
}(this, function(ApiClient, Transaction) {
  'use strict';




  /**
   * The InlineResponseDefault model module.
   * @module model/InlineResponseDefault
   * @version 0.16
   */

  /**
   * Constructs a new <code>InlineResponseDefault</code>.
   * @alias module:model/InlineResponseDefault
   * @class
   */
  var exports = function() {
    var _this = this;


  };

  /**
   * Constructs a <code>InlineResponseDefault</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InlineResponseDefault} obj Optional instance to populate.
   * @return {module:model/InlineResponseDefault} The populated <code>InlineResponseDefault</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('txid')) {
        obj['txid'] = Transaction.constructFromObject(data['txid']);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/Transaction} txid
   */
  exports.prototype['txid'] = undefined;



  return exports;
}));


