/**
 * Bitcoind
 * The REST API can be enabled with the `-rest` option. The interface runs on the same port as the JSON-RPC interface, by default port `8332` for **mainnet**, port `18332` for **testnet**, and port `18443` for **regtest**.
 *
 * OpenAPI spec version: 0.16
 * Contact: johan@lepetitbloc.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ScriptPubKey'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ScriptPubKey'));
  } else {
    // Browser globals (root is window)
    if (!root.BitcoindRestClient) {
      root.BitcoindRestClient = {};
    }
    root.BitcoindRestClient.UTxO = factory(root.BitcoindRestClient.ApiClient, root.BitcoindRestClient.ScriptPubKey);
  }
}(this, function(ApiClient, ScriptPubKey) {
  'use strict';




  /**
   * The UTxO model module.
   * @module model/UTxO
   * @version 0.16
   */

  /**
   * Constructs a new <code>UTxO</code>.
   * @alias module:model/UTxO
   * @class
   */
  var exports = function() {
    var _this = this;





  };

  /**
   * Constructs a <code>UTxO</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UTxO} obj Optional instance to populate.
   * @return {module:model/UTxO} The populated <code>UTxO</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('txvers')) {
        obj['txvers'] = ApiClient.convertToType(data['txvers'], 'Number');
      }
      if (data.hasOwnProperty('height')) {
        obj['height'] = ApiClient.convertToType(data['height'], 'Number');
      }
      if (data.hasOwnProperty('value')) {
        obj['value'] = ApiClient.convertToType(data['value'], 'Number');
      }
      if (data.hasOwnProperty('scriptPubKey')) {
        obj['scriptPubKey'] = ScriptPubKey.constructFromObject(data['scriptPubKey']);
      }
    }
    return obj;
  }

  /**
   * @member {Number} txvers
   */
  exports.prototype['txvers'] = undefined;
  /**
   * @member {Number} height
   */
  exports.prototype['height'] = undefined;
  /**
   * @member {Number} value
   */
  exports.prototype['value'] = undefined;
  /**
   * @member {module:model/ScriptPubKey} scriptPubKey
   */
  exports.prototype['scriptPubKey'] = undefined;



  return exports;
}));


