/**
 * Bitcoind
 * The REST API can be enabled with the `-rest` option. The interface runs on the same port as the JSON-RPC interface, by default port `8332` for **mainnet**, port `18332` for **testnet**, and port `18443` for **regtest**.
 *
 * OpenAPI spec version: 0.16
 * Contact: johan@lepetitbloc.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/InlineResponse200', 'model/InlineResponseDefault', 'model/MemoryPool'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/InlineResponse200'), require('../model/InlineResponseDefault'), require('../model/MemoryPool'));
  } else {
    // Browser globals (root is window)
    if (!root.BitcoindRestClient) {
      root.BitcoindRestClient = {};
    }
    root.BitcoindRestClient.MemoryPoolApi = factory(root.BitcoindRestClient.ApiClient, root.BitcoindRestClient.InlineResponse200, root.BitcoindRestClient.InlineResponseDefault, root.BitcoindRestClient.MemoryPool);
  }
}(this, function(ApiClient, InlineResponse200, InlineResponseDefault, MemoryPool) {
  'use strict';

  /**
   * MemoryPool service.
   * @module api/MemoryPoolApi
   * @version 0.16
   */

  /**
   * Constructs a new MemoryPoolApi. 
   * @alias module:api/MemoryPoolApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;



    /**
     * Returns Unspent Transaction (TX) Outputs
     * Only supports JSON as output format.
     * @param {String} txHash The transaction hash
     * @param {String} txOutput The transaction output
     * @param {module:model/String} format The expected format
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/InlineResponse200} and HTTP response
     */
    this.restGetutxosWithHttpInfo = function(txHash, txOutput, format) {
      var postBody = null;

      // verify the required parameter 'txHash' is set
      if (txHash === undefined || txHash === null) {
        throw new Error("Missing the required parameter 'txHash' when calling restGetutxos");
      }

      // verify the required parameter 'txOutput' is set
      if (txOutput === undefined || txOutput === null) {
        throw new Error("Missing the required parameter 'txOutput' when calling restGetutxos");
      }

      // verify the required parameter 'format' is set
      if (format === undefined || format === null) {
        throw new Error("Missing the required parameter 'format' when calling restGetutxos");
      }


      var pathParams = {
        'txHash': txHash,
        'txOutput': txOutput,
        'format': format
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['application/octet-stream', 'text/plain'];
      var returnType = InlineResponse200;

      return this.apiClient.callApi(
        '/getutxos/checkmempool/{txHash}-{txOutput}.{format}', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Returns Unspent Transaction (TX) Outputs
     * Only supports JSON as output format.
     * @param {String} txHash The transaction hash
     * @param {String} txOutput The transaction output
     * @param {module:model/String} format The expected format
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/InlineResponse200}
     */
    this.restGetutxos = function(txHash, txOutput, format) {
      return this.restGetutxosWithHttpInfo(txHash, txOutput, format)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Returns headers.
     * Only supports BIN and HEX as output format.
     * @param {Number} headerCount The header count
     * @param {String} blockHash The block hash
     * @param {module:model/String} format The expected format
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link 'String'} and HTTP response
     */
    this.restHeadersWithHttpInfo = function(headerCount, blockHash, format) {
      var postBody = null;

      // verify the required parameter 'headerCount' is set
      if (headerCount === undefined || headerCount === null) {
        throw new Error("Missing the required parameter 'headerCount' when calling restHeaders");
      }

      // verify the required parameter 'blockHash' is set
      if (blockHash === undefined || blockHash === null) {
        throw new Error("Missing the required parameter 'blockHash' when calling restHeaders");
      }

      // verify the required parameter 'format' is set
      if (format === undefined || format === null) {
        throw new Error("Missing the required parameter 'format' when calling restHeaders");
      }


      var pathParams = {
        'headerCount': headerCount,
        'blockHash': blockHash,
        'format': format
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['application/octet-stream', 'text/plain'];
      var returnType = 'String';

      return this.apiClient.callApi(
        '/headers/{headerCount}/{blockHash}.{format}', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Returns headers.
     * Only supports BIN and HEX as output format.
     * @param {Number} headerCount The header count
     * @param {String} blockHash The block hash
     * @param {module:model/String} format The expected format
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link 'String'}
     */
    this.restHeaders = function(headerCount, blockHash, format) {
      return this.restHeadersWithHttpInfo(headerCount, blockHash, format)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Returns transactions in the TX mempool.
     * Only supports JSON as output format.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/InlineResponseDefault} and HTTP response
     */
    this.restMempoolContentsWithHttpInfo = function() {
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = InlineResponseDefault;

      return this.apiClient.callApi(
        '/mempool/contents.json', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Returns transactions in the TX mempool.
     * Only supports JSON as output format.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/InlineResponseDefault}
     */
    this.restMempoolContents = function() {
      return this.restMempoolContentsWithHttpInfo()
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Returns various information about the TX mempool.
     * Only supports JSON as output format.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/MemoryPool} and HTTP response
     */
    this.restMempoolInfoWithHttpInfo = function() {
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = MemoryPool;

      return this.apiClient.callApi(
        '/mempool/info.json', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Returns various information about the TX mempool.
     * Only supports JSON as output format.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/MemoryPool}
     */
    this.restMempoolInfo = function() {
      return this.restMempoolInfoWithHttpInfo()
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }
  };

  return exports;
}));
