/**
 * Bitcoind
 * The REST API can be enabled with the `-rest` option. The interface runs on the same port as the JSON-RPC interface, by default port `8332` for **mainnet**, port `18332` for **testnet**, and port `18443` for **regtest**.
 *
 * OpenAPI spec version: 0.16
 * Contact: johan@lepetitbloc.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.BitcoindRestClient);
  }
}(this, function(expect, BitcoindRestClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new BitcoindRestClient.Transaction();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Transaction', function() {
    it('should create an instance of Transaction', function() {
      // uncomment below and update the code to test Transaction
      //var instance = new BitcoindRestClient.Transaction();
      //expect(instance).to.be.a(BitcoindRestClient.Transaction);
    });

    it('should have the property amount (base name: "amount")', function() {
      // uncomment below and update the code to test the property amount
      //var instance = new BitcoindRestClient.Transaction();
      //expect(instance).to.be();
    });

    it('should have the property fee (base name: "fee")', function() {
      // uncomment below and update the code to test the property fee
      //var instance = new BitcoindRestClient.Transaction();
      //expect(instance).to.be();
    });

    it('should have the property confirmations (base name: "confirmations")', function() {
      // uncomment below and update the code to test the property confirmations
      //var instance = new BitcoindRestClient.Transaction();
      //expect(instance).to.be();
    });

    it('should have the property blockhash (base name: "blockhash")', function() {
      // uncomment below and update the code to test the property blockhash
      //var instance = new BitcoindRestClient.Transaction();
      //expect(instance).to.be();
    });

    it('should have the property blockindex (base name: "blockindex")', function() {
      // uncomment below and update the code to test the property blockindex
      //var instance = new BitcoindRestClient.Transaction();
      //expect(instance).to.be();
    });

    it('should have the property blocktime (base name: "blocktime")', function() {
      // uncomment below and update the code to test the property blocktime
      //var instance = new BitcoindRestClient.Transaction();
      //expect(instance).to.be();
    });

    it('should have the property txid (base name: "txid")', function() {
      // uncomment below and update the code to test the property txid
      //var instance = new BitcoindRestClient.Transaction();
      //expect(instance).to.be();
    });

    it('should have the property txhash (base name: "txhash")', function() {
      // uncomment below and update the code to test the property txhash
      //var instance = new BitcoindRestClient.Transaction();
      //expect(instance).to.be();
    });

    it('should have the property version (base name: "version")', function() {
      // uncomment below and update the code to test the property version
      //var instance = new BitcoindRestClient.Transaction();
      //expect(instance).to.be();
    });

    it('should have the property size (base name: "size")', function() {
      // uncomment below and update the code to test the property size
      //var instance = new BitcoindRestClient.Transaction();
      //expect(instance).to.be();
    });

    it('should have the property vsize (base name: "vsize")', function() {
      // uncomment below and update the code to test the property vsize
      //var instance = new BitcoindRestClient.Transaction();
      //expect(instance).to.be();
    });

    it('should have the property locktime (base name: "locktime")', function() {
      // uncomment below and update the code to test the property locktime
      //var instance = new BitcoindRestClient.Transaction();
      //expect(instance).to.be();
    });

    it('should have the property time (base name: "time")', function() {
      // uncomment below and update the code to test the property time
      //var instance = new BitcoindRestClient.Transaction();
      //expect(instance).to.be();
    });

    it('should have the property timereceived (base name: "timereceived")', function() {
      // uncomment below and update the code to test the property timereceived
      //var instance = new BitcoindRestClient.Transaction();
      //expect(instance).to.be();
    });

    it('should have the property bip125Replaceable (base name: "bip125-replaceable")', function() {
      // uncomment below and update the code to test the property bip125Replaceable
      //var instance = new BitcoindRestClient.Transaction();
      //expect(instance).to.be();
    });

  });

}));
